# Note : 
The library is installed but can't be used bcz we haven't installed Keras seperately so good approach will be TensorBoard instead of livelossplot

In [1]:
#!pip install livelossplot --quiet

In [2]:
import tensorflow as tf
from livelossplot import PlotLossesKeras


In [3]:
# Use Keras API
model = tf.keras.Sequential()

In [4]:
tf.keras.optimizers

<module 'tensorflow.keras.optimizers' from 'C:\\Users\\Ali\\.conda\\envs\\tensor_ali\\lib\\site-packages\\tensorflow\\keras\\optimizers\\__init__.py'>

In [5]:
# Most common Loss Functions
#‘binary_crossentropy‘ for binary classification.
#‘sparse_categorical_crossentropy‘ for multi-class classification.
#‘mse‘ (mean squared error) for regression.
#loss='categorical_crossentropy', > 'mean_squared_error'


In [10]:
...
# compile the model
opt = SGD(learning_rate=0.01, momentum=0.9)
model.compile(optimizer=opt, loss='binary_crossentropy')

NameError: name 'SGD' is not defined

In [17]:
import pandas as pd
from pandas import read_csv
import numpy as np

In [7]:
# load the dataset
path = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/ionosphere.csv'
df = read_csv(path, header = None) # If header not use then , the first row will become the like column names you know
df

0   1        2        3        4        5        6        7        8   \
0     1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1     1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2     1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3     1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4     1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
..   ..  ..      ...      ...      ...      ...      ...      ...      ...   
346   1   0  0.83508  0.08298  0.73739 -0.14706  0.84349 -0.05567  0.90441   
347   1   0  0.95113  0.00419  0.95183 -0.02723  0.93438 -0.01920  0.94590   
348   1   0  0.94701 -0.00034  0.93207 -0.03227  0.95177 -0.03431  0.95584   
349   1   0  0.90608 -0.01657  0.98122 -0.01989  0.95691 -0.03646  0.85746   
350   1   0  0.84710  0.13533  0.73638 -0.06151  0.87873  0.08260  0.88928   

          9   ...       25       26       27       28       29       30  \
0    0.03760  ... -0.51171  0.41078 -0.46168  0.21266 -0.34090  0.42267   
1   -0.04549  ... -0.26569 -0.20468 -0.18401 -0.19040 -0.11593 -0.16626   
2    0.01198  ... -0.40220  0.58984 -0.22145  0.43100 -0.17365  0.60436   
3    0.00000  ...  0.90695  0.51613  1.00000  1.00000 -0.20099  0.25682   
4   -0.16399  ... -0.65158  0.13290 -0.53206  0.02431 -0.62197 -0.05707   
..       ...  ...      ...      ...      ...      ...      ...      ...   
346 -0.04622  ... -0.04202  0.83479  0.00123  1.00000  0.12815  0.86660   
347  0.01606  ...  0.01361  0.93522  0.04925  0.93159  0.08168  0.94066   
348  0.02446  ...  0.03193  0.92489  0.02542  0.92120  0.02242  0.92459   
349  0.00110  ... -0.02099  0.89147 -0.07760  0.82983 -0.17238  0.96022   
350 -0.09139  ... -0.15114  0.81147 -0.04822  0.78207 -0.00703  0.75747   

          31       32       33  34  
0   -0.54487  0.18641 -0.45300   g  
1   -0.06288 -0.13738 -0.02447   b  
2   -0.24180  0.56045 -0.38238   g  
3    1.00000 -0.32382  1.00000   b  
4   -0.59573 -0.04608 -0.65697   g  
..       ...      ...      ...  ..  
346 -0.10714  0.90546 -0.04307   g  
347 -0.00035  0.91483  0.04712   g  
348  0.00442  0.92697 -0.00577   g  
349 -0.03757  0.87403 -0.16243   g  
350 -0.06678  0.85764 -0.06151   g  

[351 rows x 35 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       351 non-null    int64  
 1   1       351 non-null    int64  
 2   2       351 non-null    float64
 3   3       351 non-null    float64
 4   4       351 non-null    float64
 5   5       351 non-null    float64
 6   6       351 non-null    float64
 7   7       351 non-null    float64
 8   8       351 non-null    float64
 9   9       351 non-null    float64
 10  10      351 non-null    float64
 11  11      351 non-null    float64
 12  12      351 non-null    float64
 13  13      351 non-null    float64
 14  14      351 non-null    float64
 15  15      351 non-null    float64
 16  16      351 non-null    float64
 17  17      351 non-null    float64
 18  18      351 non-null    float64
 19  19      351 non-null    float64
 20  20      351 non-null    float64
 21  21      351 non-null    float64
 22  22

In [8]:
df[34].describe()

count     351
unique      2
top         g
freq      225
Name: 34, dtype: object

In [14]:
X , y = df.iloc[:,:-1], df.iloc[:,-1] # Not good approach
print(X.shape)
print(y.shape)
X.head(2)

(351, 34)
(351,)


0   1        2        3        4        5        6        7    8        9   \
0   1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.0  0.03760   
1   1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.0 -0.04549   

   ...       24       25       26       27       28       29       30  \
0  ...  0.56811 -0.51171  0.41078 -0.46168  0.21266 -0.34090  0.42267   
1  ... -0.20332 -0.26569 -0.20468 -0.18401 -0.19040 -0.11593 -0.16626   

        31       32       33  
0 -0.54487  0.18641 -0.45300  
1 -0.06288 -0.13738 -0.02447  

[2 rows x 34 columns]

In [5]:
X , y = df.values[:,:-1], df.values[:,-1] # Not good approach
print(X.shape)
print(y.shape)
X

(351, 34)
(351,)


array([[1, 0, 0.99539, ..., -0.54487, 0.18641, -0.453],
       [1, 0, 1.0, ..., -0.06287999999999999, -0.13738, -0.02447],
       [1, 0, 1.0, ..., -0.2418, 0.56045, -0.38238],
       ...,
       [1, 0, 0.94701, ..., 0.00442, 0.9269700000000001, -0.00577],
       [1, 0, 0.9060799999999999, ..., -0.03757, 0.87403, -0.16243],
       [1, 0, 0.8471, ..., -0.06677999999999999, 0.85764, -0.06151]],
      dtype=object)

In [10]:
# ensure all data are floating point values
X = X.astype('float32')

In [18]:
import sklearn
from sklearn.preprocessing import LabelEncoder
y = LabelEncoder().fit_transform(y) # We basically encoded an array


In [19]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(280, 34) (71, 34) (280,) (71,)


In [21]:
# determine the number of input features
n_features = X_train.shape[1]
n_features

34

In [22]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [23]:
model = Sequential()
model.add(Dense(10, activation='relu', kernel_initializer='he_normal', input_shape=(n_features,))) #input_dim=34 (alternative)
model.add(Dense(8, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(1, activation='sigmoid'))

In [24]:
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [26]:
from livelossplot import PlotLosses
plotlosses = PlotLosses()

In [27]:
# fit the model
model.fit(X_train, y_train, epochs=150, batch_size=32, verbose=False ,callbacks=[plotlosses])

AttributeError: 'PlotLosses' object has no attribute 'set_model'

In [17]:
# evaluate the model
loss, acc = model.evaluate(X_test, y_test, verbose=2)
acc = acc*100
print('Test Accuracy: %.3f' % acc)

3/3 - 0s - loss: 0.2370 - accuracy: 0.8873
Test Accuracy: 88.732


In [18]:
X[2]

array([ 1.     ,  0.     ,  1.     , -0.03365,  1.     ,  0.00485,
        1.     , -0.12062,  0.88965,  0.01198,  0.73082,  0.05346,
        0.85443,  0.00827,  0.54591,  0.00299,  0.83775, -0.13644,
        0.75535, -0.0854 ,  0.70887, -0.27502,  0.43385, -0.12062,
        0.57528, -0.4022 ,  0.58984, -0.22145,  0.431  , -0.17365,
        0.60436, -0.2418 ,  0.56045, -0.38238], dtype=float32)

In [19]:
import numpy as np


In [31]:
arr = np.array([[ 1.     ,  0.     ,  1.     , -0.03365,  1.     ,  0.00485,
        1.     , -0.12062,  0.88965,  0.01198,  0.73082,  0.05346,
        0.85443,  0.00827,  0.54591,  0.00299,  0.83775, -0.13644,
        0.75535, -0.0854 ,  0.70887, -0.27502,  0.43385, -0.12062,
        0.57528, -0.4022 ,  0.58984, -0.22145,  0.431  , -0.17365,
        0.60436, -0.2418 ,  0.56045, -0.38238]])
#arr.reshape([1,34])
arr.shape

(1, 34)

In [33]:
# Making predictions
prediction = model.predict(arr)
print(prediction)
print('Predicted: %.3f' % prediction)
print(np.round(prediction))

[[0.99616563]]
Predicted: 0.996
[[1.]]


In [34]:
# Making prdictions
arr = X_test[20]
answer = y_test[20]
print(arr, answer)
arr = np.array([arr])
prediction = model.predict(arr)
print(prediction)
print('Predicted: %.3f' % prediction)
print(np.round(prediction))

[ 1.       0.       0.84134 -0.18362  0.43644  0.02919  0.93421 -0.00267
  0.87947  0.13795  0.81121 -0.01789  0.88559  0.54991  0.91714 -0.57486
  0.75    -0.2952   0.86676 -0.20104  1.       1.       0.4661  -0.1629
  0.90066 -0.02778  0.93358 -0.01158  0.61582 -0.32298  0.84463 -0.25706
  0.93323 -0.01425] 1
[[0.2654574]]
Predicted: 0.265
[[0.]]


In [38]:
# Making predictions
predictions = model.predict(X_test)
print([int(np.round(x[0])) for x in predictions])

[1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1]


In [41]:
# Alternate to same solution above
predictions = model.predict_classes(X_test)
predictions.tolist()

C:\Users\Ali\.conda\envs\tensor_ali\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


[[1],
 [1],
 [0],
 [1],
 [0],
 [1],
 [1],
 [1],
 [0],
 [0],
 [1],
 [1],
 [0],
 [1],
 [1],
 [0],
 [1],
 [0],
 [1],
 [0],
 [0],
 [1],
 [1],
 [1],
 [1],
 [0],
 [0],
 [0],
 [0],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [0],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1]]